DROP USER IF EXISTS '$MARIADB_DB_USER'@'%';
CREATE USER '$MARIADB_DB_USER'@'%' IDENTIFIED BY '$MARIADB_DB_PASS';

GRANT ALL PRIVILEGES ON $MARIADB_DB_NAME.* TO '$MARIADB_DB_USER'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;